GET http://localhost:3000/movies?year=2019

###
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "Avengers 1",
    "createdAt": "2018-01-01",
    "year": 2019,
    "category": "SF"
}

####
POST http://localhost:3000/login
Content-Type: application/json

{
   "username": "user",
   "password": "password"
}

####
GET http://localhost:3000/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJ1c2VyIiwiaWF0IjoxNTU4MDk5MDAyLCJleHAiOjE1NTgxMDI2MDJ9.U_s0Dm_cyndfKLthnK0-Dh3SJDqAzmjl8pa91Wr1CEs